port: 7880
rtc:
  port_range_start: 10000
  port_range_end: 60000
  use_external_ip: false
  node_ip: 172.22.0.10
  congestion_control:
    stream_allocator:
      min_channel_capacity: 10000000000
keys:
  devkey: secret
room:
  auto_create: true
  departure_timeout: 5
  empty_timeout: 10
logging:
  level: info
