apiVersion: call.zip/v1
kind: VideoCallStressTest
metadata:
  name: 250-viewer-bots
spec:
  plugin: jitsi
  conference:
    name: test
    usersPerRoom: 10
    totalRooms: 25
    cameras:
      perRoom: 0
      fileType: ivf
      videoCodec: vp9
      directory: '~/vp9_ivf_videos'
    joinPolicy:
      concurrency: 10
      alwaysRetryFailedJoins: true
      joinStartSpacing: 2s
    recording:
      enabled: false
      directory: './vp9_ivf_videos'
  network:
    serverIP: $env:SERVER_IP
  pluginConfig:  # plugin-specific internal configuration
    jitsi:
      _boshURL: 'https://{{spec.network.serverIP}}/http-bind'
      _domain: '{{spec.network.serverIP}}'
  logging:
    console: true
    directory: '/var/log/call-zip'
    streams:
      - name: general
        level: info
      - name: signaling
        level: debug
      - name: media
        level: info
      - name: packets
        level: info
      - name: video_stats
        level: info
